/* Generated by Yosys 0_8 (git sha1 a58571d0, clang 10_0_0-4ubuntu1 -fPIC -Os) */

 
module iob_cache(clk, reset, valid, addr, wdata, wstrb, rdata, ready, debug, mem_valid, mem_addr, mem_wdata, mem_wstrb, mem_rdata, mem_ready);

// module iob_cache(clk, reset, valid, addr, wdata, wstrb, rdata, ready, debug, force_inv_in, force_inv_out, wtb_empty_in, wtb_empty_out, mem_valid, mem_addr, mem_wdata, mem_wstrb, mem_rdata, mem_ready);
   
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire [2:0] _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
   
  wire _0011_;
   
  wire _0012_;
   
  wire _0013_;
   
  wire [3:0] _0014_;
   
  wire _0015_;
   
  wire _0016_;
   
  wire _0017_;
  wire _0018_;
  wire _0019_;
   
  wire [63:0] _0020_;
   
  wire _0021_;
   
  wire [7:0] _0022_;
   
  wire _0023_;
   
  wire [7:0] _0024_;
   
  wire _0025_;
   
  wire _0026_;
   
  wire _0027_;
   
  wire _0028_;
   
  wire _0029_;
   
  wire _0030_;
   
  wire _0031_;
   
  wire _0032_;
   
  wire [7:0] _0033_;
   
  wire [31:0] _0034_;
   
  wire _0035_;
   
  wire _0036_;
   
  wire _0037_;
   
  wire _0038_;
   
  wire _0039_;
   
  wire _0040_;
   
  wire _0041_;
   
  wire _0042_;
   
  wire _0043_;
   
  wire _0044_;
   
  wire [31:0] _0045_;
   
  wire _0046_;
   
  wire [31:0] _0047_;
   
  wire [31:0] _0048_;
  wire [7:0] _0049_;
  wire [7:0] _0050_;
   
  wire _0051_;
   
  wire _0052_;
   
  wire [7:0] _0053_;
   
  wire [7:0] _0054_;
   
  wire [31:0] _0055_;
   
  wire [31:0] _0056_;
   
  wire [63:0] _0057_;
   
  wire [2:0] _0058_;
   
  wire [7:0] _0059_;
   
  wire [7:0] _0060_;
   
  wire [7:0] _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire [7:0] _0077_;
  wire [7:0] _0078_;
  wire [7:0] _0079_;
  wire [7:0] _0080_;
  wire [7:0] _0081_;
  wire [7:0] _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire [7:0] _0091_;
  wire [7:0] _0092_;
  wire [7:0] _0093_;
  wire [7:0] _0094_;
  wire [7:0] _0095_;
  wire [7:0] _0096_;
  wire [7:0] _0097_;
  wire [7:0] _0098_;
   
  wire [7:0] _0099_;
  wire [7:0] _0100_;
  wire [7:0] _0101_;
  wire [2:0] _0102_;
  wire [7:0] _0103_;
   
  wire [2:0] _0104_;
   
  wire [7:0] _0105_;
   
  wire [7:0] _0106_;
   
  wire [7:0] _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire [7:0] _0123_;
  wire [7:0] _0124_;
  wire [7:0] _0125_;
  wire [7:0] _0126_;
  wire [7:0] _0127_;
  wire [7:0] _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire [7:0] _0137_;
  wire [7:0] _0138_;
  wire [7:0] _0139_;
  wire [7:0] _0140_;
  wire [7:0] _0141_;
  wire [7:0] _0142_;
  wire [7:0] _0143_;
  wire [7:0] _0144_;
   
  wire [7:0] _0145_;
  wire [7:0] _0146_;
  wire [7:0] _0147_;
  wire [2:0] _0148_;
  wire [7:0] _0149_;
   
  wire [2:0] _0150_;
   
  wire [7:0] _0151_;
   
  wire [7:0] _0152_;
   
  wire [7:0] _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire [7:0] _0169_;
  wire [7:0] _0170_;
  wire [7:0] _0171_;
  wire [7:0] _0172_;
  wire [7:0] _0173_;
  wire [7:0] _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire [7:0] _0183_;
  wire [7:0] _0184_;
  wire [7:0] _0185_;
  wire [7:0] _0186_;
  wire [7:0] _0187_;
  wire [7:0] _0188_;
  wire [7:0] _0189_;
  wire [7:0] _0190_;
   
  wire [7:0] _0191_;
  wire [7:0] _0192_;
  wire [7:0] _0193_;
  wire [2:0] _0194_;
  wire [7:0] _0195_;
   
  wire [2:0] _0196_;
   
  wire [7:0] _0197_;
   
  wire [7:0] _0198_;
   
  wire [7:0] _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire [7:0] _0215_;
  wire [7:0] _0216_;
  wire [7:0] _0217_;
  wire [7:0] _0218_;
  wire [7:0] _0219_;
  wire [7:0] _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire [7:0] _0229_;
  wire [7:0] _0230_;
  wire [7:0] _0231_;
  wire [7:0] _0232_;
  wire [7:0] _0233_;
  wire [7:0] _0234_;
  wire [7:0] _0235_;
  wire [7:0] _0236_;
   
  wire [7:0] _0237_;
  wire [7:0] _0238_;
  wire [7:0] _0239_;
  wire [2:0] _0240_;
  wire [7:0] _0241_;
   
  wire [2:0] _0242_;
   
  wire [7:0] _0243_;
   
  wire [7:0] _0244_;
   
  wire [7:0] _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire [7:0] _0261_;
  wire [7:0] _0262_;
  wire [7:0] _0263_;
  wire [7:0] _0264_;
  wire [7:0] _0265_;
  wire [7:0] _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire [7:0] _0275_;
  wire [7:0] _0276_;
  wire [7:0] _0277_;
  wire [7:0] _0278_;
  wire [7:0] _0279_;
  wire [7:0] _0280_;
  wire [7:0] _0281_;
  wire [7:0] _0282_;
   
  wire [7:0] _0283_;
  wire [7:0] _0284_;
  wire [7:0] _0285_;
  wire [2:0] _0286_;
  wire [7:0] _0287_;
   
  wire [2:0] _0288_;
   
  wire [7:0] _0289_;
   
  wire [7:0] _0290_;
   
  wire [7:0] _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire [7:0] _0307_;
  wire [7:0] _0308_;
  wire [7:0] _0309_;
  wire [7:0] _0310_;
  wire [7:0] _0311_;
  wire [7:0] _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire [7:0] _0321_;
  wire [7:0] _0322_;
  wire [7:0] _0323_;
  wire [7:0] _0324_;
  wire [7:0] _0325_;
  wire [7:0] _0326_;
  wire [7:0] _0327_;
  wire [7:0] _0328_;
   
  wire [7:0] _0329_;
  wire [7:0] _0330_;
  wire [7:0] _0331_;
  wire [2:0] _0332_;
  wire [7:0] _0333_;
   
  wire [2:0] _0334_;
   
  wire [7:0] _0335_;
   
  wire [7:0] _0336_;
   
  wire [7:0] _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire [7:0] _0353_;
  wire [7:0] _0354_;
  wire [7:0] _0355_;
  wire [7:0] _0356_;
  wire [7:0] _0357_;
  wire [7:0] _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire [7:0] _0367_;
  wire [7:0] _0368_;
  wire [7:0] _0369_;
  wire [7:0] _0370_;
  wire [7:0] _0371_;
  wire [7:0] _0372_;
  wire [7:0] _0373_;
  wire [7:0] _0374_;
   
  wire [7:0] _0375_;
  wire [7:0] _0376_;
  wire [7:0] _0377_;
  wire [2:0] _0378_;
  wire [7:0] _0379_;
   
  wire [2:0] _0380_;
   
  wire [7:0] _0381_;
   
  wire [7:0] _0382_;
   
  wire [7:0] _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire [7:0] _0399_;
  wire [7:0] _0400_;
  wire [7:0] _0401_;
  wire [7:0] _0402_;
  wire [7:0] _0403_;
  wire [7:0] _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire [7:0] _0413_;
  wire [7:0] _0414_;
  wire [7:0] _0415_;
  wire [7:0] _0416_;
  wire [7:0] _0417_;
  wire [7:0] _0418_;
  wire [7:0] _0419_;
  wire [7:0] _0420_;
   
  wire [7:0] _0421_;
  wire [7:0] _0422_;
  wire [7:0] _0423_;
  wire [2:0] _0424_;
  wire [7:0] _0425_;
   
  wire [2:0] _0426_;
   
  wire [5:0] _0427_;
   
  wire [5:0] _0428_;
   
  wire [5:0] _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire [5:0] _0445_;
  wire [5:0] _0446_;
  wire [5:0] _0447_;
  wire [5:0] _0448_;
  wire [5:0] _0449_;
  wire [5:0] _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire [5:0] _0459_;
  wire [5:0] _0460_;
  wire [5:0] _0461_;
  wire [5:0] _0462_;
  wire [5:0] _0463_;
  wire [5:0] _0464_;
  wire [5:0] _0465_;
  wire [5:0] _0466_;
   
  wire [5:0] _0467_;
  wire [5:0] _0468_;
  wire [5:0] _0469_;
  wire [2:0] _0470_;
  wire [5:0] _0471_;
   
  input [11:0] addr;
   
  wire back_end_mem_valid_read ;
   
  wire back_end_mem_valid_write ;
   
  reg back_end_read_addr ;
   
  wire back_end_read_fsm_read_valid ;
   
  wire back_end_read_fsm_replace ;
   
  wire back_end_read_fsm_replace_valid ;
  reg [2:0] back_end_read_fsm_state ;
   
  wire back_end_read_fsm_word_counter ;
   
  wire back_end_write_fsm_ready ;
   
  reg back_end_write_fsm_state ;
   
  wire back_end_write_fsm_valid ;
   
  wire back_end_write_fsm_word_counter ;
   
  reg back_end_write_fsm_word_counter_reg ;
   
  reg [11:0] cache_memory_addr_reg ;
   
  reg cache_memory_dirty ;
   
  reg [7:0] cache_memory_dirty_reg ;
   
  wire cache_memory_hit ;
   
  reg [5:0] cache_memory_line_tag ;
   
  wire [7:0] cache_memory_line_wstrb ;
   
  wire [2:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr ;
   
  wire [31:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in ;
   
  wire cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7 ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7 ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7 ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7 ;
   
  wire [3:0] cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we ;
   
  wire [2:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7 ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7 ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7 ;
   
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6 ;
  reg [7:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7 ;
   
  wire [3:0] cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we ;
   
  reg cache_memory_offset_prev ;
   
  wire cache_memory_raw ;
   
  wire cache_memory_read_access ;
  reg [5:0] cache_memory_tag_memory_ram_0 ;
  reg [5:0] cache_memory_tag_memory_ram_1 ;
  reg [5:0] cache_memory_tag_memory_ram_2 ;
  reg [5:0] cache_memory_tag_memory_ram_3 ;
  reg [5:0] cache_memory_tag_memory_ram_4 ;
  reg [5:0] cache_memory_tag_memory_ram_5 ;
  reg [5:0] cache_memory_tag_memory_ram_6 ;
  reg [5:0] cache_memory_tag_memory_ram_7 ;
   
  reg cache_memory_v ;
   
  reg [7:0] cache_memory_v_reg ;
   
  reg cache_memory_valid_reg ;
   
  wire cache_memory_way_hit ;
   
  reg cache_memory_way_hit_prev ;
   
  reg [31:0] cache_memory_wdata_reg ;
   
  wire cache_memory_write_access ;
   
  reg cache_memory_write_hit_prev ;
   
  reg [3:0] cache_memory_wstrb_reg ;
   
  input clk;
   
  output [1:0] debug;
   
//   input force_inv_in;
   
//   output force_inv_out;
   
  output [11:0] mem_addr;
   
  input [31:0] mem_rdata;
   
  input mem_ready;
   
  output mem_valid;
   
  output [31:0] mem_wdata;
   
  output [3:0] mem_wstrb;
   
  output [31:0] rdata;
   
  output ready;
   
  input reset;
   
  input valid;
   
  input [31:0] wdata;
   
  input [3:0] wstrb;
//    
//   input wtb_empty_in;
//    
//   output wtb_empty_out;
  assign mem_valid = back_end_mem_valid_read  |   back_end_mem_valid_write ;
//   assign { mem_addr[11:6], mem_addr[2] } = back_end_mem_valid_read  ?   { addr[9:4], back_end_read_fsm_word_counter  } : { cache_memory_line_tag , back_end_write_fsm_word_counter  };
  assign _0000_ = back_end_read_addr  +   mem_ready;
  assign _0001_ = _0007_ & back_end_read_fsm_state [0];
  assign _0002_ = _0008_ & back_end_read_fsm_state [2];
  assign _0003_ = _0009_ & back_end_read_fsm_state [2];
  assign _0004_ = _0010_ & back_end_read_fsm_state [2];
  assign _0005_ = back_end_read_fsm_replace_valid  & back_end_read_fsm_state [0];
  assign _0006_[0] = | { _0001_, back_end_read_fsm_state [1] };
  assign _0006_[2] = | { _0005_, _0003_, _0004_ };
  always @(posedge clk or posedge reset)
    if (reset)
      back_end_read_fsm_state  <= 3'h1;
    else
      back_end_read_fsm_state  <= { _0006_[2], _0002_, _0006_[0] };
  assign _0007_ = ~ back_end_read_fsm_replace_valid ;
  assign _0008_ = { back_end_read_addr , mem_ready } == 2'h3;
  assign _0009_ = ~ mem_ready;
  assign _0010_ = { back_end_read_addr , mem_ready } == 2'h1;
  assign _0011_ = ~   back_end_read_addr ;
  assign _0012_ = _0009_ |   _0011_;
  always @(posedge clk)
      back_end_read_addr  <= back_end_read_fsm_word_counter ;
  assign back_end_read_fsm_replace = back_end_read_fsm_state [0] ? 1'h0 : 1'h1;
  assign back_end_read_fsm_word_counter  = back_end_read_fsm_state [2] ?   _0000_ : 1'h0;
  assign back_end_read_fsm_read_valid  = back_end_read_fsm_state [2] ?   mem_ready : 1'h0;
  assign back_end_mem_valid_read  = back_end_read_fsm_state [2] ?   _0012_ : 1'h0;
  assign _0015_ = back_end_write_fsm_word_counter_reg  +   mem_ready;
  assign _0016_ = mem_ready &   back_end_write_fsm_word_counter_reg ;
  assign _0017_ = ~   back_end_write_fsm_valid ;
  always @(posedge clk or posedge reset)
    if (reset)
      back_end_write_fsm_state  <= 1'h0;
    else
      back_end_write_fsm_state  <= _0013_;
  always @(posedge clk)
      back_end_write_fsm_word_counter_reg  <= back_end_write_fsm_word_counter ;
  assign _0014_[3] = back_end_write_fsm_valid  ?   1'h1 : 1'h0;
  assign mem_wstrb[3] = back_end_write_fsm_state  ?   1'h1 : _0014_[3];
  assign back_end_write_fsm_ready  = back_end_write_fsm_state  ?   1'h0 : _0017_;
  assign back_end_write_fsm_word_counter  = back_end_write_fsm_state  ?   _0015_ : 1'h0;
  assign back_end_mem_valid_write  = back_end_write_fsm_state  ?   1'h1 : 1'h0;
  assign _0018_ = _0016_ ?   1'h0 : 1'h1;
  assign _0019_ = back_end_write_fsm_valid  ?   1'h1 : 1'h0;
  assign _0013_ = back_end_write_fsm_state  ?   _0018_ : _0019_;
//   assign { _0020_[63:32], mem_wdata } = { cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout  } >>   { 26'h0000000, back_end_write_fsm_word_counter , 5'h00 };
  assign _0025_ = _0041_ &   back_end_write_fsm_ready ;
  assign _0026_ = _0025_ &   cache_memory_valid_reg ;
  assign back_end_read_fsm_replace_valid  = _0026_ &   _0043_;
  assign _0027_ = cache_memory_write_hit_prev  &   _0037_;
  assign _0028_ = _0027_ &   _0038_;
  assign cache_memory_raw  = _0028_ &   cache_memory_read_access ;
  assign _0029_ = cache_memory_way_hit  &   _0043_;
  assign cache_memory_hit  = _0029_ &   _0044_;
  assign ready = cache_memory_hit  &   cache_memory_valid_reg ;
  assign cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we  = { cache_memory_way_hit , cache_memory_way_hit , cache_memory_way_hit , cache_memory_way_hit  } &   cache_memory_line_wstrb [3:0];
  assign cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we  = { cache_memory_way_hit , cache_memory_way_hit , cache_memory_way_hit , cache_memory_way_hit  } &   cache_memory_line_wstrb [7:4];
  assign _0031_ = _0030_ &   _0039_;
  assign _0030_ = cache_memory_write_access  &   cache_memory_way_hit ;
  assign _0032_ = _0030_ &   cache_memory_addr_reg [2];
  assign _0033_ = cache_memory_wstrb_reg  &   { 4'h0, cache_memory_write_access , cache_memory_write_access , cache_memory_write_access , cache_memory_write_access  };
  assign cache_memory_way_hit  = _0040_ &   cache_memory_v ;
  assign _0034_ = cache_memory_dirty_reg  &   _0045_;
  assign _0035_ = cache_memory_write_access  &   cache_memory_hit ;
  assign _0036_ = cache_memory_write_access  &   _0046_;
  assign back_end_write_fsm_valid  = _0036_ &   cache_memory_dirty ;
  assign cache_memory_write_access  = _0051_ &   cache_memory_valid_reg ;
  assign cache_memory_read_access  = _0042_ &   cache_memory_valid_reg ;
  assign _0037_ = cache_memory_way_hit_prev  ==   cache_memory_way_hit ;
  assign _0038_ = cache_memory_offset_prev  ==   cache_memory_addr_reg [2];
  assign _0039_ = ~   cache_memory_addr_reg [2];
  assign _0040_ = cache_memory_addr_reg [11:6] ==   cache_memory_line_tag ;
  assign _0041_ = !   cache_memory_way_hit ;
  assign _0042_ = !   _0051_;
  assign _0043_ = ~   back_end_read_fsm_replace ;
  assign _0044_ = ~   cache_memory_raw ;
  assign _0045_ = ~   _0056_;
  assign _0046_ = ~   cache_memory_way_hit ;
  assign _0047_ = cache_memory_v_reg  |   _0055_;
  assign _0048_ = cache_memory_dirty_reg  |   _0056_;
  always @(posedge clk)
      cache_memory_dirty  <= _0021_;
  always @(posedge clk or posedge reset)
    if (reset)
      cache_memory_dirty_reg  <= 8'h00;
    else
      cache_memory_dirty_reg  <= _0022_;
  always @(posedge clk)
      cache_memory_v  <= _0023_;
  always @(posedge clk or posedge reset)
    if (reset)
      cache_memory_v_reg  <= 8'h00;
    else
      cache_memory_v_reg  <= _0024_;
  always @(posedge clk)
      cache_memory_write_hit_prev  <= cache_memory_write_access ;
  always @(posedge clk)
      cache_memory_offset_prev  <= cache_memory_addr_reg [2];
  always @(posedge clk)
      cache_memory_way_hit_prev  <= cache_memory_way_hit ;
  assign _0049_ = _0035_ ?   _0048_[7:0] : cache_memory_dirty_reg ;
  assign _0022_ = back_end_write_fsm_valid  ?   _0034_[7:0] : _0049_;
  assign _0023_ = 1'h0 ?   1'h0 : _0052_;
  assign _0050_ = back_end_read_fsm_replace_valid  ?   _0047_[7:0] : cache_memory_v_reg ;
  assign _0024_ = 1'h0 ?   8'h00 : _0050_;
  assign cache_memory_line_wstrb  = back_end_read_fsm_replace  ?   _0053_ : _0054_;
  assign _0051_ = |   { cache_memory_wstrb_reg [0], cache_memory_wstrb_reg [1], cache_memory_wstrb_reg [2], cache_memory_wstrb_reg [3] };
  wire [2:0] mask;
  assign mask = 3'd1 << addr[3:1];
  assign _0052_ = | (cache_memory_v_reg & mask);
  assign _0021_ = | (cache_memory_dirty_reg & mask);
//   assign _0052_ = cache_memory_v_reg [addr[3:1] +: 1];
//   assign _0021_ = cache_memory_dirty_reg [addr[3:1] +: 1];
  assign _0053_ = { 4'h0, back_end_read_fsm_read_valid , back_end_read_fsm_read_valid , back_end_read_fsm_read_valid , back_end_read_fsm_read_valid  } <<  { 5'h0, back_end_read_addr , 2'h0 };
  assign _0054_ = _0033_ <<  { 5'h0, cache_memory_addr_reg [2], 2'h0 };
  assign _0055_ = 32'd1 <<  {29'h0,addr[3:1]};
  assign _0056_ = 32'd1 << {29'h0,cache_memory_addr_reg [5:3]};
  wire [63:0] w1;
  assign w1 = { cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout  } >> { 58'h0000000, cache_memory_addr_reg [2], 5'h00 };
  assign rdata = w1[31:0];
//   assign { _0057_[63:32], rdata } = { cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout , cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout  } >> { 58'h0000000, cache_memory_addr_reg [2], 5'h00 };
  assign cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr  = _0031_ ?   cache_memory_addr_reg [5:3] : addr[3:1];
  assign cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr  = _0032_ ?   cache_memory_addr_reg [5:3] : addr[3:1];
  assign cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in  = back_end_read_fsm_replace  ?   mem_rdata : cache_memory_wdata_reg ;
  assign _0074_ = ~ _0058_[0];
  assign _0075_ = ~ _0058_[1];
  assign _0076_ = ~ _0058_[2];
  assign _0062_ = _0075_ & _0076_;
  assign _0063_ = _0074_ & _0062_;
  assign _0064_ = _0058_[0] & _0062_;
  assign _0065_ = _0058_[1] & _0076_;
  assign _0066_ = _0074_ & _0065_;
  assign _0067_ = _0058_[0] & _0065_;
  assign _0068_ = _0075_ & _0058_[2];
  assign _0069_ = _0074_ & _0068_;
  assign _0070_ = _0058_[0] & _0068_;
  assign _0071_ = _0058_[1] & _0058_[2];
  assign _0072_ = _0074_ & _0071_;
  assign _0073_ = _0058_[0] & _0071_;
  assign _0099_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [2] ? _0078_ : _0077_;
  assign _0077_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0080_ : _0079_;
  assign _0078_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0082_ : _0081_;
  assign _0079_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0 ;
  assign _0080_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2 ;
  assign _0081_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4 ;
  assign _0082_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6 ;
  assign _0083_ = _0063_ & _0060_[7];
  assign _0084_ = _0064_ & _0060_[7];
  assign _0085_ = _0066_ & _0060_[7];
  assign _0086_ = _0067_ & _0060_[7];
  assign _0087_ = _0069_ & _0060_[7];
  assign _0088_ = _0070_ & _0060_[7];
  assign _0089_ = _0072_ & _0060_[7];
  assign _0090_ = _0073_ & _0060_[7];
  assign _0091_ = _0083_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0 ;
  assign _0092_ = _0084_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1 ;
  assign _0093_ = _0085_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2 ;
  assign _0094_ = _0086_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3 ;
  assign _0095_ = _0087_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4 ;
  assign _0096_ = _0088_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5 ;
  assign _0097_ = _0089_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6 ;
  assign _0098_ = _0090_ ? _0059_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0  <= _0091_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1  <= _0092_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2  <= _0093_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3  <= _0094_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4  <= _0095_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5  <= _0096_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6  <= _0097_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7  <= _0098_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout  <= _0061_;
  assign _0100_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [0] ?   1'h1 : 1'h0;
  assign _0060_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0100_[7] : 1'h0;
  assign _0101_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [0] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [7:0] : 8'hxx;
  assign _0059_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0101_ : 8'hxx;
  assign _0102_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [0] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0058_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0102_ : 3'hx;
  assign _0103_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [0] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout  : _0099_;
  assign _0061_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0103_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout ;
  assign _0120_ = ~ _0104_[0];
  assign _0121_ = ~ _0104_[1];
  assign _0122_ = ~ _0104_[2];
  assign _0108_ = _0121_ & _0122_;
  assign _0109_ = _0120_ & _0108_;
  assign _0110_ = _0104_[0] & _0108_;
  assign _0111_ = _0104_[1] & _0122_;
  assign _0112_ = _0120_ & _0111_;
  assign _0113_ = _0104_[0] & _0111_;
  assign _0114_ = _0121_ & _0104_[2];
  assign _0115_ = _0120_ & _0114_;
  assign _0116_ = _0104_[0] & _0114_;
  assign _0117_ = _0104_[1] & _0104_[2];
  assign _0118_ = _0120_ & _0117_;
  assign _0119_ = _0104_[0] & _0117_;
  assign _0145_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [2] ? _0124_ : _0123_;
  assign _0123_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0126_ : _0125_;
  assign _0124_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0128_ : _0127_;
  assign _0125_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0 ;
  assign _0126_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2 ;
  assign _0127_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4 ;
  assign _0128_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6 ;
  assign _0129_ = _0109_ & _0106_[7];
  assign _0130_ = _0110_ & _0106_[7];
  assign _0131_ = _0112_ & _0106_[7];
  assign _0132_ = _0113_ & _0106_[7];
  assign _0133_ = _0115_ & _0106_[7];
  assign _0134_ = _0116_ & _0106_[7];
  assign _0135_ = _0118_ & _0106_[7];
  assign _0136_ = _0119_ & _0106_[7];
  assign _0137_ = _0129_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0 ;
  assign _0138_ = _0130_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1 ;
  assign _0139_ = _0131_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2 ;
  assign _0140_ = _0132_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3 ;
  assign _0141_ = _0133_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4 ;
  assign _0142_ = _0134_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5 ;
  assign _0143_ = _0135_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6 ;
  assign _0144_ = _0136_ ? _0105_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0  <= _0137_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1  <= _0138_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2  <= _0139_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3  <= _0140_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4  <= _0141_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5  <= _0142_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6  <= _0143_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7  <= _0144_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout  <= _0107_;
  assign _0146_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [1] ?   1'h1 : 1'h0;
  assign _0106_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0146_[7] : 1'h0;
  assign _0147_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [1] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [15:8] : 8'hxx;
  assign _0105_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0147_ : 8'hxx;
  assign _0148_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [1] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0104_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0148_ : 3'hx;
  assign _0149_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [1] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout  : _0145_;
  assign _0107_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0149_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout ;
  assign _0166_ = ~ _0150_[0];
  assign _0167_ = ~ _0150_[1];
  assign _0168_ = ~ _0150_[2];
  assign _0154_ = _0167_ & _0168_;
  assign _0155_ = _0166_ & _0154_;
  assign _0156_ = _0150_[0] & _0154_;
  assign _0157_ = _0150_[1] & _0168_;
  assign _0158_ = _0166_ & _0157_;
  assign _0159_ = _0150_[0] & _0157_;
  assign _0160_ = _0167_ & _0150_[2];
  assign _0161_ = _0166_ & _0160_;
  assign _0162_ = _0150_[0] & _0160_;
  assign _0163_ = _0150_[1] & _0150_[2];
  assign _0164_ = _0166_ & _0163_;
  assign _0165_ = _0150_[0] & _0163_;
  assign _0191_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [2] ? _0170_ : _0169_;
  assign _0169_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0172_ : _0171_;
  assign _0170_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0174_ : _0173_;
  assign _0171_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0 ;
  assign _0172_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2 ;
  assign _0173_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4 ;
  assign _0174_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6 ;
  assign _0175_ = _0155_ & _0152_[7];
  assign _0176_ = _0156_ & _0152_[7];
  assign _0177_ = _0158_ & _0152_[7];
  assign _0178_ = _0159_ & _0152_[7];
  assign _0179_ = _0161_ & _0152_[7];
  assign _0180_ = _0162_ & _0152_[7];
  assign _0181_ = _0164_ & _0152_[7];
  assign _0182_ = _0165_ & _0152_[7];
  assign _0183_ = _0175_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0 ;
  assign _0184_ = _0176_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1 ;
  assign _0185_ = _0177_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2 ;
  assign _0186_ = _0178_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3 ;
  assign _0187_ = _0179_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4 ;
  assign _0188_ = _0180_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5 ;
  assign _0189_ = _0181_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6 ;
  assign _0190_ = _0182_ ? _0151_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0  <= _0183_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1  <= _0184_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2  <= _0185_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3  <= _0186_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4  <= _0187_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5  <= _0188_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6  <= _0189_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7  <= _0190_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout  <= _0153_;
  assign _0192_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [2] ?   1'h1 : 1'h0;
  assign _0152_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0192_[7] : 1'h0;
  assign _0193_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [2] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [23:16] : 8'hxx;
  assign _0151_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0193_ : 8'hxx;
  assign _0194_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [2] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0150_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0194_ : 3'hx;
  assign _0195_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [2] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout  : _0191_;
  assign _0153_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0195_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout ;
  assign _0212_ = ~ _0196_[0];
  assign _0213_ = ~ _0196_[1];
  assign _0214_ = ~ _0196_[2];
  assign _0200_ = _0213_ & _0214_;
  assign _0201_ = _0212_ & _0200_;
  assign _0202_ = _0196_[0] & _0200_;
  assign _0203_ = _0196_[1] & _0214_;
  assign _0204_ = _0212_ & _0203_;
  assign _0205_ = _0196_[0] & _0203_;
  assign _0206_ = _0213_ & _0196_[2];
  assign _0207_ = _0212_ & _0206_;
  assign _0208_ = _0196_[0] & _0206_;
  assign _0209_ = _0196_[1] & _0196_[2];
  assign _0210_ = _0212_ & _0209_;
  assign _0211_ = _0196_[0] & _0209_;
  assign _0237_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [2] ? _0216_ : _0215_;
  assign _0215_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0218_ : _0217_;
  assign _0216_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [1] ? _0220_ : _0219_;
  assign _0217_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0 ;
  assign _0218_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2 ;
  assign _0219_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4 ;
  assign _0220_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6 ;
  assign _0221_ = _0201_ & _0198_[7];
  assign _0222_ = _0202_ & _0198_[7];
  assign _0223_ = _0204_ & _0198_[7];
  assign _0224_ = _0205_ & _0198_[7];
  assign _0225_ = _0207_ & _0198_[7];
  assign _0226_ = _0208_ & _0198_[7];
  assign _0227_ = _0210_ & _0198_[7];
  assign _0228_ = _0211_ & _0198_[7];
  assign _0229_ = _0221_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0 ;
  assign _0230_ = _0222_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1 ;
  assign _0231_ = _0223_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2 ;
  assign _0232_ = _0224_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3 ;
  assign _0233_ = _0225_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4 ;
  assign _0234_ = _0226_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5 ;
  assign _0235_ = _0227_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6 ;
  assign _0236_ = _0228_ ? _0197_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0  <= _0229_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1  <= _0230_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2  <= _0231_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3  <= _0232_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4  <= _0233_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5  <= _0234_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6  <= _0235_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7  <= _0236_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout  <= _0199_;
  assign _0238_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [3] ?   1'h1 : 1'h0;
  assign _0198_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0238_[7] : 1'h0;
  assign _0239_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [3] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [31:24] : 8'hxx;
  assign _0197_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0239_ : 8'hxx;
  assign _0240_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [3] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0196_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0240_ : 3'hx;
  assign _0241_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_we [3] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout  : _0237_;
  assign _0199_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0241_ : cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout ;
  assign _0258_ = ~ _0242_[0];
  assign _0259_ = ~ _0242_[1];
  assign _0260_ = ~ _0242_[2];
  assign _0246_ = _0259_ & _0260_;
  assign _0247_ = _0258_ & _0246_;
  assign _0248_ = _0242_[0] & _0246_;
  assign _0249_ = _0242_[1] & _0260_;
  assign _0250_ = _0258_ & _0249_;
  assign _0251_ = _0242_[0] & _0249_;
  assign _0252_ = _0259_ & _0242_[2];
  assign _0253_ = _0258_ & _0252_;
  assign _0254_ = _0242_[0] & _0252_;
  assign _0255_ = _0242_[1] & _0242_[2];
  assign _0256_ = _0258_ & _0255_;
  assign _0257_ = _0242_[0] & _0255_;
  assign _0283_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [2] ? _0262_ : _0261_;
  assign _0261_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0264_ : _0263_;
  assign _0262_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0266_ : _0265_;
  assign _0263_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0 ;
  assign _0264_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2 ;
  assign _0265_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4 ;
  assign _0266_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6 ;
  assign _0267_ = _0247_ & _0244_[7];
  assign _0268_ = _0248_ & _0244_[7];
  assign _0269_ = _0250_ & _0244_[7];
  assign _0270_ = _0251_ & _0244_[7];
  assign _0271_ = _0253_ & _0244_[7];
  assign _0272_ = _0254_ & _0244_[7];
  assign _0273_ = _0256_ & _0244_[7];
  assign _0274_ = _0257_ & _0244_[7];
  assign _0275_ = _0267_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0 ;
  assign _0276_ = _0268_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1 ;
  assign _0277_ = _0269_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2 ;
  assign _0278_ = _0270_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3 ;
  assign _0279_ = _0271_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4 ;
  assign _0280_ = _0272_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5 ;
  assign _0281_ = _0273_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6 ;
  assign _0282_ = _0274_ ? _0243_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_0  <= _0275_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_1  <= _0276_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_2  <= _0277_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_3  <= _0278_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_4  <= _0279_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_5  <= _0280_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_6  <= _0281_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_ram_7  <= _0282_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout  <= _0245_;
  assign _0284_[7] = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [0] ?   1'h1 : 1'h0;
  assign _0244_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0284_[7] : 1'h0;
  assign _0285_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [0] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [7:0] : 8'hxx;
  assign _0243_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0285_ : 8'hxx;
  assign _0286_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [0] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0242_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0286_ : 3'hx;
  assign _0287_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [0] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout  : _0283_;
  assign _0245_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0287_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_0_iob_cache_mem_dout ;
  assign _0304_ = ~ _0288_[0];
  assign _0305_ = ~ _0288_[1];
  assign _0306_ = ~ _0288_[2];
  assign _0292_ = _0305_ & _0306_;
  assign _0293_ = _0304_ & _0292_;
  assign _0294_ = _0288_[0] & _0292_;
  assign _0295_ = _0288_[1] & _0306_;
  assign _0296_ = _0304_ & _0295_;
  assign _0297_ = _0288_[0] & _0295_;
  assign _0298_ = _0305_ & _0288_[2];
  assign _0299_ = _0304_ & _0298_;
  assign _0300_ = _0288_[0] & _0298_;
  assign _0301_ = _0288_[1] & _0288_[2];
  assign _0302_ = _0304_ & _0301_;
  assign _0303_ = _0288_[0] & _0301_;
  assign _0329_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [2] ? _0308_ : _0307_;
  assign _0307_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0310_ : _0309_;
  assign _0308_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0312_ : _0311_;
  assign _0309_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0 ;
  assign _0310_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2 ;
  assign _0311_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4 ;
  assign _0312_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6 ;
  assign _0313_ = _0293_ & _0290_[7];
  assign _0314_ = _0294_ & _0290_[7];
  assign _0315_ = _0296_ & _0290_[7];
  assign _0316_ = _0297_ & _0290_[7];
  assign _0317_ = _0299_ & _0290_[7];
  assign _0318_ = _0300_ & _0290_[7];
  assign _0319_ = _0302_ & _0290_[7];
  assign _0320_ = _0303_ & _0290_[7];
  assign _0321_ = _0313_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0 ;
  assign _0322_ = _0314_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1 ;
  assign _0323_ = _0315_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2 ;
  assign _0324_ = _0316_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3 ;
  assign _0325_ = _0317_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4 ;
  assign _0326_ = _0318_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5 ;
  assign _0327_ = _0319_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6 ;
  assign _0328_ = _0320_ ? _0289_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_0  <= _0321_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_1  <= _0322_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_2  <= _0323_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_3  <= _0324_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_4  <= _0325_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_5  <= _0326_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_6  <= _0327_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_ram_7  <= _0328_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout  <= _0291_;
  assign _0330_[7] = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [1] ?   1'h1 : 1'h0;
  assign _0290_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0330_[7] : 1'h0;
  assign _0331_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [1] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [15:8] : 8'hxx;
  assign _0289_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0331_ : 8'hxx;
  assign _0332_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [1] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0288_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0332_ : 3'hx;
  assign _0333_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [1] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout  : _0329_;
  assign _0291_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0333_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_1_iob_cache_mem_dout ;
  assign _0350_ = ~ _0334_[0];
  assign _0351_ = ~ _0334_[1];
  assign _0352_ = ~ _0334_[2];
  assign _0338_ = _0351_ & _0352_;
  assign _0339_ = _0350_ & _0338_;
  assign _0340_ = _0334_[0] & _0338_;
  assign _0341_ = _0334_[1] & _0352_;
  assign _0342_ = _0350_ & _0341_;
  assign _0343_ = _0334_[0] & _0341_;
  assign _0344_ = _0351_ & _0334_[2];
  assign _0345_ = _0350_ & _0344_;
  assign _0346_ = _0334_[0] & _0344_;
  assign _0347_ = _0334_[1] & _0334_[2];
  assign _0348_ = _0350_ & _0347_;
  assign _0349_ = _0334_[0] & _0347_;
  assign _0375_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [2] ? _0354_ : _0353_;
  assign _0353_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0356_ : _0355_;
  assign _0354_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0358_ : _0357_;
  assign _0355_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0 ;
  assign _0356_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2 ;
  assign _0357_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4 ;
  assign _0358_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6 ;
  assign _0359_ = _0339_ & _0336_[7];
  assign _0360_ = _0340_ & _0336_[7];
  assign _0361_ = _0342_ & _0336_[7];
  assign _0362_ = _0343_ & _0336_[7];
  assign _0363_ = _0345_ & _0336_[7];
  assign _0364_ = _0346_ & _0336_[7];
  assign _0365_ = _0348_ & _0336_[7];
  assign _0366_ = _0349_ & _0336_[7];
  assign _0367_ = _0359_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0 ;
  assign _0368_ = _0360_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1 ;
  assign _0369_ = _0361_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2 ;
  assign _0370_ = _0362_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3 ;
  assign _0371_ = _0363_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4 ;
  assign _0372_ = _0364_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5 ;
  assign _0373_ = _0365_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6 ;
  assign _0374_ = _0366_ ? _0335_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_0  <= _0367_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_1  <= _0368_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_2  <= _0369_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_3  <= _0370_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_4  <= _0371_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_5  <= _0372_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_6  <= _0373_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_ram_7  <= _0374_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout  <= _0337_;
  assign _0376_[7] = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [2] ?   1'h1 : 1'h0;
  assign _0336_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0376_[7] : 1'h0;
  assign _0377_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [2] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [23:16] : 8'hxx;
  assign _0335_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0377_ : 8'hxx;
  assign _0378_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [2] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0334_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0378_ : 3'hx;
  assign _0379_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [2] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout  : _0375_;
  assign _0337_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0379_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_2_iob_cache_mem_dout ;
  assign _0396_ = ~ _0380_[0];
  assign _0397_ = ~ _0380_[1];
  assign _0398_ = ~ _0380_[2];
  assign _0384_ = _0397_ & _0398_;
  assign _0385_ = _0396_ & _0384_;
  assign _0386_ = _0380_[0] & _0384_;
  assign _0387_ = _0380_[1] & _0398_;
  assign _0388_ = _0396_ & _0387_;
  assign _0389_ = _0380_[0] & _0387_;
  assign _0390_ = _0397_ & _0380_[2];
  assign _0391_ = _0396_ & _0390_;
  assign _0392_ = _0380_[0] & _0390_;
  assign _0393_ = _0380_[1] & _0380_[2];
  assign _0394_ = _0396_ & _0393_;
  assign _0395_ = _0380_[0] & _0393_;
  assign _0421_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [2] ? _0400_ : _0399_;
  assign _0399_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0402_ : _0401_;
  assign _0400_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [1] ? _0404_ : _0403_;
  assign _0401_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0 ;
  assign _0402_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2 ;
  assign _0403_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4 ;
  assign _0404_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr [0] ? cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7  : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6 ;
  assign _0405_ = _0385_ & _0382_[7];
  assign _0406_ = _0386_ & _0382_[7];
  assign _0407_ = _0388_ & _0382_[7];
  assign _0408_ = _0389_ & _0382_[7];
  assign _0409_ = _0391_ & _0382_[7];
  assign _0410_ = _0392_ & _0382_[7];
  assign _0411_ = _0394_ & _0382_[7];
  assign _0412_ = _0395_ & _0382_[7];
  assign _0413_ = _0405_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0 ;
  assign _0414_ = _0406_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1 ;
  assign _0415_ = _0407_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2 ;
  assign _0416_ = _0408_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3 ;
  assign _0417_ = _0409_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4 ;
  assign _0418_ = _0410_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5 ;
  assign _0419_ = _0411_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6 ;
  assign _0420_ = _0412_ ? _0381_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7 ;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_0  <= _0413_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_1  <= _0414_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_2  <= _0415_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_3  <= _0416_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_4  <= _0417_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_5  <= _0418_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_6  <= _0419_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_ram_7  <= _0420_;
  always @(posedge clk)
      cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout  <= _0383_;
  assign _0422_[7] = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [3] ?   1'h1 : 1'h0;
  assign _0382_[7] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0422_[7] : 1'h0;
  assign _0423_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [3] ?   cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_data_in [31:24] : 8'hxx;
  assign _0381_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0423_ : 8'hxx;
  assign _0424_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [3] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_addr  : 3'hx;
  assign _0380_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0424_ : 3'hx;
  assign _0425_ = cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_we [3] ?   cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout  : _0421_;
  assign _0383_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0425_ : cache_memory_n_ways_block_0_line2mem_block_1_BE_FE_block_0_cache_memory_ram_3_iob_cache_mem_dout ;
  assign _0442_ = ~ _0426_[0];
  assign _0443_ = ~ _0426_[1];
  assign _0444_ = ~ _0426_[2];
  assign _0430_ = _0443_ & _0444_;
  assign _0431_ = _0442_ & _0430_;
  assign _0432_ = _0426_[0] & _0430_;
  assign _0433_ = _0426_[1] & _0444_;
  assign _0434_ = _0442_ & _0433_;
  assign _0435_ = _0426_[0] & _0433_;
  assign _0436_ = _0443_ & _0426_[2];
  assign _0437_ = _0442_ & _0436_;
  assign _0438_ = _0426_[0] & _0436_;
  assign _0439_ = _0426_[1] & _0426_[2];
  assign _0440_ = _0442_ & _0439_;
  assign _0441_ = _0426_[0] & _0439_;
  assign _0467_ = addr[3] ? _0446_ : _0445_;
  assign _0445_ = addr[2] ? _0448_ : _0447_;
  assign _0446_ = addr[2] ? _0450_ : _0449_;
  assign _0447_ = addr[1] ? cache_memory_tag_memory_ram_1  : cache_memory_tag_memory_ram_0 ;
  assign _0448_ = addr[1] ? cache_memory_tag_memory_ram_3  : cache_memory_tag_memory_ram_2 ;
  assign _0449_ = addr[1] ? cache_memory_tag_memory_ram_5  : cache_memory_tag_memory_ram_4 ;
  assign _0450_ = addr[1] ? cache_memory_tag_memory_ram_7  : cache_memory_tag_memory_ram_6 ;
  assign _0451_ = _0431_ & _0428_[5];
  assign _0452_ = _0432_ & _0428_[5];
  assign _0453_ = _0434_ & _0428_[5];
  assign _0454_ = _0435_ & _0428_[5];
  assign _0455_ = _0437_ & _0428_[5];
  assign _0456_ = _0438_ & _0428_[5];
  assign _0457_ = _0440_ & _0428_[5];
  assign _0458_ = _0441_ & _0428_[5];
  assign _0459_ = _0451_ ? _0427_ : cache_memory_tag_memory_ram_0 ;
  assign _0460_ = _0452_ ? _0427_ : cache_memory_tag_memory_ram_1 ;
  assign _0461_ = _0453_ ? _0427_ : cache_memory_tag_memory_ram_2 ;
  assign _0462_ = _0454_ ? _0427_ : cache_memory_tag_memory_ram_3 ;
  assign _0463_ = _0455_ ? _0427_ : cache_memory_tag_memory_ram_4 ;
  assign _0464_ = _0456_ ? _0427_ : cache_memory_tag_memory_ram_5 ;
  assign _0465_ = _0457_ ? _0427_ : cache_memory_tag_memory_ram_6 ;
  assign _0466_ = _0458_ ? _0427_ : cache_memory_tag_memory_ram_7 ;
  always @(posedge clk)
      cache_memory_tag_memory_ram_0  <= _0459_;
  always @(posedge clk)
      cache_memory_tag_memory_ram_1  <= _0460_;
  always @(posedge clk)
      cache_memory_tag_memory_ram_2  <= _0461_;
  always @(posedge clk)
      cache_memory_tag_memory_ram_3  <= _0462_;
  always @(posedge clk)
      cache_memory_tag_memory_ram_4  <= _0463_;
  always @(posedge clk)
      cache_memory_tag_memory_ram_5  <= _0464_;
  always @(posedge clk)
      cache_memory_tag_memory_ram_6  <= _0465_;
  always @(posedge clk)
      cache_memory_tag_memory_ram_7  <= _0466_;
  always @(posedge clk)
      cache_memory_line_tag  <= _0429_;
  assign _0468_[5] = back_end_read_fsm_replace_valid  ?   1'h1 : 1'h0;
  assign _0428_[5] = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0468_[5] : 1'h0;
  assign _0469_ = back_end_read_fsm_replace_valid  ?  cache_memory_addr_reg [11:6] : 6'hxx;
  assign _0427_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0469_ : 6'hxx;
  assign _0470_ = back_end_read_fsm_replace_valid  ?   addr[3:1] : 3'hx;
  assign _0426_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0470_ : 3'hx;
  assign _0471_ = back_end_read_fsm_replace_valid  ?   cache_memory_line_tag  : _0467_;
  assign _0429_ = cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  ?   _0471_ : cache_memory_line_tag ;
  assign cache_memory_n_ways_block_0_line2mem_block_0_BE_FE_block_0_cache_memory_en  = valid |   cache_memory_valid_reg ;
  always @(posedge clk or posedge reset)
    if (reset)
      cache_memory_valid_reg  <= 1'h0;
    else
      cache_memory_valid_reg  <= valid;
  always @(posedge clk or posedge reset)
    if (reset)
      cache_memory_addr_reg  <= 12'h000;
    else
      cache_memory_addr_reg  <= {addr[9:0],2'h0};
  always @(posedge clk or posedge reset)
    if (reset)
      cache_memory_wdata_reg  <= 32'd0;
    else
      cache_memory_wdata_reg  <= wdata;
  always @(posedge clk or posedge reset)
    if (reset)
      cache_memory_wstrb_reg  <= 4'h0;
    else
      cache_memory_wstrb_reg  <= wstrb;
  assign debug = 2'h0;
//   assign { mem_addr[5:3], mem_addr[1:0] } = { addr[3:1], 2'h0 };
//   assign mem_wstrb[2:0] = { mem_wstrb[3], mem_wstrb[3], mem_wstrb[3] };

//  always @(posedge clk)
//     begin
//     //   if(ready == 1'b1)
//         // debug <= 2'b11;
//         if (wstrb == 1'b1) begin
        
//           if( addr == 10'h1234 && wdata == 32'hDEADBEEF )
//             begin
//                 // if (ready) begin
//                      $display("WRITE");
//                 // end
             

              
//               // $display("%b", rdata);
             
//             //   debug <= 2'b01;
//               // debugOutput2 <= 1;
//               // debugOutput3 <= 0;
//               // debugOutput4 <= 1;
//             end

        

//          end
//     end


    // assign wdata = 32'hDEADBEEF;

    // always @(posedge clk) begin

    //     if (addr == 10'h1234) begin
    //         if (wstrb == 1'b1 ) begin
    //             $display("WRITE");
    //         end
    //         else begin
    //             if (ready == 1'b1 && rdata == 32'hDEADBEEF) begin
    //                   $display("READ");
    //             end
    //         end
    //     end
    
    // end


    // always @(posedge clk)
    // begin
    //   if(ready == 1'b1)
    //     // debug <= 2'b11;
    //     if (wstrb == 1'b0) begin
        
    //       if( addr == 10'h1234 && rdata == 32'hDEADBEEF )
    //         begin
             

              
    //           // $display("%b", rdata);
    //           $display("FOUND");
    //         //   debug <= 2'b01;
    //           // debugOutput2 <= 1;
    //           // debugOutput3 <= 0;
    //           // debugOutput4 <= 1;
    //         end

        

    //      end
    // end

    // assign wdata = 32'hDEADBEEF;

    // always @(posedge clk) begin

    //     if (addr == 10'h1234) begin
    //         if (wstrb == 1'b1 ) begin
    //             $display("WRITE");
    //         end
    //         else begin
    //             if (ready == 1'b1 && rdata == 32'hDEADBEEF) begin
    //                   $display("READ");
    //             end
    //         end
    //     end
    
    // end
    // assert property (ready==1 & wstrb==0 & addr == 12'h1234 & valid == 1 |-> cache_memory_hit==1);

    // assert property (wdata==32'hCAFEFEED && wstrb==1 && addr == 12'h1234 |=> ready==1);
    assert property (ready==1  |->  wdata==32'hCAFEFEED && wstrb==1 && addr == 12'h1234);
 
endmodule
